#!/bin/bash
# ssl-auto-provision.sh
# Script tự động cấp SSL certificate cho custom domains
# Chạy sau khi domain được verify thành công

set -e
set -o pipefail

LOG_FILE="/var/log/ssl-provision.log"
CERTBOT="/usr/bin/certbot"
CERT_DIR="/etc/letsencrypt/live"
NGINX_WEBROOT="${NGINX_WEBROOT:-/var/www/certbot}"
DOMAIN_CONF_DIR="${DOMAIN_CONF_DIR:-/root/uknow/nginx-domains}"
FRONTEND_CONTAINER="${FRONTEND_CONTAINER:-uknow-campaign-frontend}"
DEFAULT_WEBROOT="/root/uknow/certbot"
CERT_CHANGED=0
CONFIG_CHANGED=0

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" | tee -a "$LOG_FILE" >&2
    exit 1
}

# Check root
if [[ $EUID -ne 0 ]]; then
   error "Script này cần chạy với quyền root"
fi

# Get domain from argument
DOMAIN="$1"

if [[ -z "$DOMAIN" ]]; then
    echo "Usage: $0 <domain>"
    echo "Example: $0 digibook.com.vn"
    exit 1
fi

log "Starting SSL provision for: $DOMAIN"

detect_container_webroot() {
    docker inspect \
        --format "{{range .Mounts}}{{if eq .Destination \"$NGINX_WEBROOT\"}}{{.Source}}{{end}}{{end}}" \
        "$FRONTEND_CONTAINER" 2>/dev/null || true
}

if [[ -z "${WEBROOT:-}" ]]; then
    DETECTED_WEBROOT="$(detect_container_webroot)"
    WEBROOT="${DETECTED_WEBROOT:-$DEFAULT_WEBROOT}"
fi

log "Using certbot webroot: $WEBROOT (nginx path: $NGINX_WEBROOT)"

# Create webroot if not exists
mkdir -p "$WEBROOT/.well-known/acme-challenge"
chown -R www-data:www-data "$WEBROOT" 2>/dev/null || true
mkdir -p "$DOMAIN_CONF_DIR"

verify_webroot_challenge() {
    local token body
    token="uknow-acme-check-$(date +%s)-$$"
    echo "ok" > "$WEBROOT/.well-known/acme-challenge/$token"

    body="$(curl --max-time 10 -fsS "http://$DOMAIN/.well-known/acme-challenge/$token" 2>/dev/null || true)"
    rm -f "$WEBROOT/.well-known/acme-challenge/$token"

    if [[ "$body" != "ok" ]]; then
        error "ACME webroot is not reachable for $DOMAIN. Expected token from $WEBROOT via http://$DOMAIN/.well-known/acme-challenge/$token, got '${body:-<empty>}'"
    fi
}

# Check if certificate already exists
if [[ -d "$CERT_DIR/$DOMAIN" ]]; then
    log "Certificate already exists for $DOMAIN, checking if valid..."
    if openssl x509 -checkend 0 -in "$CERT_DIR/$DOMAIN/fullchain.pem" > /dev/null 2>&1; then
        log "Certificate is still valid. No need to renew."
    else
        log "Certificate expired or expiring soon, renewing..."
        if $CERTBOT renew --cert-name "$DOMAIN" --webroot -w "$WEBROOT" --non-interactive 2>&1 | tee -a "$LOG_FILE"; then
            CERT_CHANGED=1
            log "Certificate renewed or checked successfully"
        else
            log "Renewal failed or not due yet"
        fi
    fi
else
    # Get new certificate
    log "Requesting SSL certificate from Let's Encrypt..."
    verify_webroot_challenge

    if $CERTBOT certonly \
        --webroot \
        -w "$WEBROOT" \
        -d "$DOMAIN" \
        --non-interactive \
        --agree-tos \
        --email support@digiso.vn \
        --keep-until-expiring \
        2>&1 | tee -a "$LOG_FILE"; then
        log "Certificate obtained successfully!"
        CERT_CHANGED=1
    else
        error "Failed to obtain certificate for $DOMAIN"
    fi
fi

# Create nginx config for this domain
log "Creating Nginx configuration for $DOMAIN..."
SSL_CONFIG="$DOMAIN_CONF_DIR/ssl-$DOMAIN.conf"
TMP_SSL_CONFIG="$(mktemp)"

cat > "$TMP_SSL_CONFIG" << EOF
# SSL config for $DOMAIN - Auto-generated by ssl-auto-provision.sh
# DO NOT EDIT MANUALLY - Will be overwritten on renewal

server {
    listen 80;
    server_name $DOMAIN;

    location /.well-known/acme-challenge/ {
        root $NGINX_WEBROOT;
        try_files \$uri =404;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate $CERT_DIR/$DOMAIN/fullchain.pem;
    ssl_certificate_key $CERT_DIR/$DOMAIN/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    client_max_body_size 50m;

    # ACME challenge
    location /.well-known/acme-challenge/ {
        root $NGINX_WEBROOT;
        try_files \$uri =404;
    }

    location / {
        resolver 127.0.0.11 valid=10s ipv6=off;
        set \$backend_upstream http://uknow-campaign-backend:5001;
        proxy_pass \$backend_upstream;
        proxy_http_version 1.1;

        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

if [[ -f "$SSL_CONFIG" ]] && cmp -s "$TMP_SSL_CONFIG" "$SSL_CONFIG"; then
    rm -f "$TMP_SSL_CONFIG"
    log "Nginx config unchanged at $SSL_CONFIG"
else
    mv "$TMP_SSL_CONFIG" "$SSL_CONFIG"
    CONFIG_CHANGED=1
    log "Nginx config written at $SSL_CONFIG"
fi

if [[ "$CERT_CHANGED" -eq 0 && "$CONFIG_CHANGED" -eq 0 ]]; then
    log "Certificate and Nginx config unchanged; skipping Nginx reload"
    log "SSL provision completed for: $DOMAIN"
    exit 0
fi

# Test and reload nginx inside the frontend container. The host writes configs to
# DOMAIN_CONF_DIR, which is mounted into the container at /etc/nginx/domains.
log "Testing Nginx configuration in container: $FRONTEND_CONTAINER..."
if docker exec "$FRONTEND_CONTAINER" nginx -t 2>&1 | tee -a "$LOG_FILE"; then
    log "Reloading Nginx in container: $FRONTEND_CONTAINER..."
    docker exec "$FRONTEND_CONTAINER" nginx -s reload
    log "Nginx container reloaded successfully"
else
    error "Nginx config test failed in frontend container"
fi

log "SSL provision completed for: $DOMAIN"

# Verify SSL
log "Verifying SSL certificate..."
if [[ -f "$CERT_DIR/$DOMAIN/fullchain.pem" ]]; then
    echo | openssl s_client -connect "$DOMAIN:443" -servername "$DOMAIN" 2>/dev/null | openssl x509 -noout -dates || log "Warning: Could not verify SSL in browser"
    log "Certificate details:"
    openssl x509 -in "$CERT_DIR/$DOMAIN/fullchain.pem" -noout -subject -issuer -dates 2>&1 | tee -a "$LOG_FILE"
else
    log "Warning: Certificate file not found"
fi

exit 0
