#!/bin/bash
# ssl-auto-provision.sh
# Script tự động cấp SSL certificate cho custom domains
# Chạy sau khi domain được verify thành công

set -e

LOG_FILE="/var/log/ssl-provision.log"
CERTBOT="/usr/bin/certbot"
NGINX="/usr/sbin/nginx"
CERT_DIR="/etc/letsencrypt/live"
WEBROOT="/var/www/certbot"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" | tee -a "$LOG_FILE" >&2
    exit 1
}

# Check root
if [[ $EUID -ne 0 ]]; then
   error "Script này cần chạy với quyền root"
fi

# Get domain from argument
DOMAIN="$1"

if [[ -z "$DOMAIN" ]]; then
    echo "Usage: $0 <domain>"
    echo "Example: $0 digibook.com.vn"
    exit 1
fi

log "Starting SSL provision for: $DOMAIN"

# Create webroot if not exists
mkdir -p "$WEBROOT/.well-known/acme-challenge"
chown -R www-data:www-data "$WEBROOT" 2>/dev/null || true

# Check if certificate already exists
if [[ -d "$CERT_DIR/$DOMAIN" ]]; then
    log "Certificate already exists for $DOMAIN, checking if valid..."
    if openssl x509 -checkend 0 -in "$CERT_DIR/$DOMAIN/fullchain.pem" > /dev/null 2>&1; then
        log "Certificate is still valid. No need to renew."
    else
        log "Certificate expired or expiring soon, renewing..."
        $CERTBOT renew --cert-name "$DOMAIN" --webroot -w "$WEBROOT" --non-interactive || log "Renewal failed or not due yet"
    fi
else
    # Get new certificate
    log "Requesting SSL certificate from Let's Encrypt..."

    if $CERTBOT certonly \
        --webroot \
        -w "$WEBROOT" \
        -d "$DOMAIN" \
        --non-interactive \
        --agree-tos \
        --email support@digiso.vn \
        --keep-until-expiring \
        2>&1 | tee -a "$LOG_FILE"; then
        log "Certificate obtained successfully!"
    else
        error "Failed to obtain certificate for $DOMAIN"
    fi
fi

# Create nginx config for this domain
log "Creating Nginx configuration for $DOMAIN..."
SSL_CONFIG="/etc/nginx/conf.d/ssl-$DOMAIN.conf"

cat > "$SSL_CONFIG" << EOF
# SSL config for $DOMAIN - Auto-generated by ssl-auto-provision.sh
# DO NOT EDIT MANUALLY - Will be overwritten on renewal

server {
    listen 80;
    server_name $DOMAIN;

    location /.well-known/acme-challenge/ {
        root $WEBROOT;
        try_files \$uri =404;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate $CERT_DIR/$DOMAIN/fullchain.pem;
    ssl_certificate_key $CERT_DIR/$DOMAIN/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    client_max_body_size 50m;

    # ACME challenge
    location /.well-known/acme-challenge/ {
        root $WEBROOT;
        try_files \$uri =404;
    }

    location / {
        resolver 127.0.0.11 valid=10s ipv6=off;
        set \$backend_upstream http://uknow-campaign-backend:5001;
        proxy_pass \$backend_upstream;
        proxy_http_version 1.1;

        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

log "Nginx config created at $SSL_CONFIG"

# Test and reload nginx
log "Testing Nginx configuration..."
if $NGINX -t 2>&1 | tee -a "$LOG_FILE"; then
    log "Reloading Nginx..."
    $NGINX -s reload
    log "Nginx reloaded successfully"
else
    error "Nginx config test failed"
fi

log "SSL provision completed for: $DOMAIN"

# Verify SSL
log "Verifying SSL certificate..."
if [[ -f "$CERT_DIR/$DOMAIN/fullchain.pem" ]]; then
    echo | openssl s_client -connect "$DOMAIN:443" -servername "$DOMAIN" 2>/dev/null | openssl x509 -noout -dates || log "Warning: Could not verify SSL in browser"
    log "Certificate details:"
    openssl x509 -in "$CERT_DIR/$DOMAIN/fullchain.pem" -noout -subject -issuer -dates 2>&1 | tee -a "$LOG_FILE"
else
    log "Warning: Certificate file not found"
fi

exit 0
